spring:
  profiles: container
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
  datasource:
    url: jdbc:/mysql://mysql:3306/k8portcourse1?createDatabaseIfNotExist=true?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: password
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto=none:

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka
    fetchRegistry: true
  instance:
    leaseRenewalIntervalInSeconds: 30
    leaseExpirationDurationInSeconds: 90

ribbon:
  eureka:
    enabled: true
